let r1='',r2='',tlSel=new Set(),tlMode='peli',rChart,tlChart,tmChart;
const RK=['PPG','RPG','APG','SPG','BPG','FGp','AT'];
const RL=['Pisteet','Levypallot','Syötöt','Riistot','Blokit','FG%','AST/TO'];
function norm(k,v){const mx=Math.max(0,...players.map(p=>pStats[p]?.[k]||0));return mx?Math.round(v/mx*100):0}
function buildRadarChips(){[['c1',0],['c2',1]].forEach(([id,idx])=>{const el=document.getElementById(id);el.innerHTML='';players.forEach((p,i)=>{const b=document.createElement('button');b.className='chip'+(p===(idx?r2:r1)?' on':'');if(b.classList.contains('on'))b.style.background=PAL[i%PAL.length];b.textContent=p;b.onclick=()=>{idx?r2=p:r1=p;buildRadarChips();buildRadar()};el.appendChild(b)})})}
function buildRadar(){if(!r1||!r2)return;const ctx=document.getElementById('radarC');rChart?.destroy();rChart=new Chart(ctx,{type:'radar',data:{labels:RL,datasets:[{label:r1,data:RK.map(k=>norm(k,pStats[r1]?.[k]||0)),borderColor:'#f0a500',backgroundColor:'rgba(240,165,0,.15)'},{label:r2,data:RK.map(k=>norm(k,pStats[r2]?.[k]||0)),borderColor:'#5b8dee',backgroundColor:'rgba(91,141,238,.15)'}]},options:{scales:{r:{min:0,max:100,ticks:{display:false},grid:{color:'rgba(255,255,255,.08)'},pointLabels:{color:'#e8eaf0'},angleLines:{color:'rgba(255,255,255,.08)'}}},plugins:{legend:{labels:{color:'#e8eaf0'}}}}})}
function setTlMode(mode){tlMode=mode;document.querySelectorAll('#btnPeli,#btnKumu').forEach(b=>b.classList.toggle('active',(b.id==='btnPeli')===(mode==='peli')));buildTimeline()}
function buildTlChips(){const el=document.getElementById('tlChips');el.innerHTML='';players.forEach((p,i)=>{const b=document.createElement('button');b.className='chip'+(tlSel.has(p)?' on':'');if(tlSel.has(p))b.style.background=PAL[i%PAL.length];b.textContent=p;b.onclick=()=>{tlSel.has(p)?tlSel.delete(p):tlSel.add(p);buildTlChips();buildTimeline()};el.appendChild(b)})}
function buildTimeline(){const gns=tGames.map(g=>n(g[COL.ottelu]));const labels=tGames.map(g=>`O${g[COL.ottelu]} ${(g[COL.vastustaja]||'').split(' ')[0]}`);const datasets=[...tlSel].map(p=>{const col=PAL[players.indexOf(p)%PAL.length],vals=gns.map(gn=>(gData[p]||[]).find(d=>d.g===gn)?.pts??null);let sum=0;return{label:p,data:tlMode==='kumu'?vals.map(v=>v==null?null:(sum+=v)):vals,borderColor:col,backgroundColor:col+'33',tension:.3,spanGaps:true}});tlChart?.destroy();tlChart=new Chart(document.getElementById('tlC'),{type:'line',data:{labels,datasets},options:{plugins:{legend:{labels:{color:'#e8eaf0'}}},scales:{x:{ticks:{color:'#7a8090'}},y:{ticks:{color:'#7a8090'},title:{display:true,text:tlMode==='kumu'?'Pisteet yhteensä':'Pisteet per peli',color:'#7a8090'}}}}})}
function buildTeamChart(){const labels=tGames.map(g=>`O${g[COL.ottelu]} ${(g[COL.vastustaja]||'').split(' ')[0]}`);tmChart?.destroy();tmChart=new Chart(document.getElementById('teamC'),{type:'bar',data:{labels,datasets:[{label:'PP Pisteet',data:tGames.map(g=>n(g[COL.omaPts])),backgroundColor:tGames.map(g=>g[COL.tulos]==='Voitto'?'#3ecf8e':'#e05a2b')},{label:'Vastustaja',data:tGames.map(g=>n(g[COL.vastPts])),backgroundColor:'rgba(255,255,255,.2)'}]},options:{plugins:{legend:{labels:{color:'#e8eaf0'}}},scales:{x:{ticks:{color:'#7a8090'}},y:{ticks:{color:'#7a8090'},beginAtZero:true}}}})}
function buildShooting(){const el=document.getElementById('sg');el.innerHTML='';players.filter(p=>pStats[p].hasAdv).sort((a,b)=>pStats[b].FGp-pStats[a].FGp).forEach(p=>{const d=pStats[p];el.insertAdjacentHTML('beforeend',`<div class="sc"><div class="sc-name">${p}</div><div class="big">${d.PPG}</div><div class="biglbl">PPG · EFF ${d.EFF}</div><div class="bl"><span>FG%</span><span>${d.FGp}%</span></div><div class="bt"><div class="bf bfg" style="width:${d.FGp}%"></div></div><div class="bl"><span>3PT%</span><span>${d.P3p}%</span></div><div class="bt"><div class="bf b3p" style="width:${d.P3p}%"></div></div></div>`)})}
