const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbyyDbxGfzz3nuDHoqRB6rTy9tYj1vDWbPW159O2OQzsmEfRFCnN92h_bp6qfAMwFo4vMA/exec';
const PAL=['#f0a500','#5b8dee','#3ecf8e','#e05a2b','#c084fc','#f472b6','#34d399','#fb923c','#60a5fa','#a78bfa','#fbbf24','#4ade80'];
const COL={nimi:'Nimi',ottelu:'Ottelunumero',vastustaja:'Vastustaja',pisteet:'Pisteet',kotiv:'Koti/Vieras',tulos:'Lopputulos',kausi:'Kausi',sarja:'Sarja/Harjoitus',omaPts:'Omat pisteet',vastPts:'Vastustajan pisteet',fgm:'FGM',fga:'FGA',t3m:'3PTM',t3a:'3PTA',ftm:'FTM',fta:'FTA',orb:'ORB',drb:'DRB',rb:'RB',ast:'AST',stl:'STL',blk:'BLK',to:'TO',pf:'PF'};
let allRows=[],seasons=[],curSeason='',pStats={},gData={},tGames=[],players=[];
function n(v){return(v==null||v===''||isNaN(v))?0:+v}
function hasAdvancedStats(r){return [COL.fgm,COL.fga,COL.t3m,COL.t3a,COL.ftm,COL.fta,COL.orb,COL.drb,COL.rb,COL.ast,COL.stl,COL.blk,COL.to,COL.pf].some(k=>r[k]!==null&&r[k]!==undefined&&r[k]!=='')}
function parseMinutes(v){if(v==null||v===''||v===0)return null;if(typeof v==='number')return +(v*24*60).toFixed(1);const s=String(v).trim();const iso=s.match(/T(\d{2}):(\d{2}):(\d{2})/);if(iso)return +(+iso[1]*60 + +iso[2] + +iso[3]/60).toFixed(1);const p=s.split(':').map(Number);if(p.length===3&&p.every(Number.isFinite))return +(p[0]*60+p[1]+p[2]/60).toFixed(1);if(p.length===2&&p.every(Number.isFinite))return +(p[0]*60+p[1]).toFixed(1);return null}
async function loadData(){const res=await fetch(APPS_SCRIPT_URL);if(!res.ok)throw new Error('HTTP '+res.status);allRows=await res.json();seasons=[...new Set(allRows.map(r=>r[COL.kausi]).filter(Boolean))].sort().reverse();curSeason=seasons[0]||'';processSeason(curSeason)}
function seasonRows(season=curSeason){return allRows.filter(r=>r[COL.kausi]===season&&r[COL.sarja]==='Sarja')}
function processSeason(s){const rows=seasonRows(s),games={};rows.forEach(r=>{if(!games[r[COL.ottelu]])games[r[COL.ottelu]]=r});tGames=Object.values(games).sort((a,b)=>n(a[COL.ottelu])-n(b[COL.ottelu]));const pm={};rows.forEach(r=>{const nm=r[COL.nimi];if(!nm)return;if(!pm[nm])pm[nm]={games:new Set(),pts:0,fgm:0,fga:0,t3m:0,t3a:0,ftm:0,fta:0,rb:0,ast:0,stl:0,blk:0,to:0,adv:false};const p=pm[nm];p.games.add(r[COL.ottelu]);p.pts+=n(r[COL.pisteet]);p.fgm+=n(r[COL.fgm]);p.fga+=n(r[COL.fga]);p.t3m+=n(r[COL.t3m]);p.t3a+=n(r[COL.t3a]);p.ftm+=n(r[COL.ftm]);p.fta+=n(r[COL.fta]);p.rb+=n(r[COL.rb]);p.ast+=n(r[COL.ast]);p.stl+=n(r[COL.stl]);p.blk+=n(r[COL.blk]);p.to+=n(r[COL.to]);p.adv ||= hasAdvancedStats(r)});pStats={};for(const [nm,p] of Object.entries(pm)){const g=p.games.size||1;const eff=p.pts+p.rb+p.ast+p.stl+p.blk-p.to-(p.fga-p.fgm)-(p.fta-p.ftm);pStats[nm]={Pelit:p.games.size,PPG:+(p.pts/g).toFixed(1),RPG:+(p.rb/g).toFixed(1),APG:+(p.ast/g).toFixed(1),SPG:+(p.stl/g).toFixed(1),BPG:+(p.blk/g).toFixed(1),FGp:p.fga?+(p.fgm/p.fga*100).toFixed(1):0,P3p:p.t3a?+(p.t3m/p.t3a*100).toFixed(1):0,P3a:+(p.t3a/g).toFixed(1),AT:p.to?+(p.ast/p.to).toFixed(2):0,EFF:+(eff/g).toFixed(1),hasAdv:p.adv}}
gData={};rows.forEach(r=>{const nm=r[COL.nimi];if(!nm)return;(gData[nm]??=[]).push({g:n(r[COL.ottelu]),pts:n(r[COL.pisteet]),opp:r[COL.vastustaja]})});Object.values(gData).forEach(a=>a.sort((a,b)=>a.g-b.g));players=Object.keys(pStats).sort()}
function rowsForSelectedSeasons(selected){const ss=selected?.size?[...selected]:[curSeason];return allRows.filter(r=>ss.includes(r[COL.kausi])&&r[COL.sarja]==='Sarja')}
