let tblMode='yht',selectedSeasons=new Set(),activePlayer=null,activeOpp=null,sKeyP='pts',sDescP=true,sKeyO='label',sDescO=false;
const PLAYER_COLS=['pts','min','fgm','fga','fgpct','t2m','t2a','t2pct','t3m','t3a','t3pct','ftm','fta','ftpct','orb','drb','rb','ast','stl','blk','to','pf'];
const OPP_COLS=['oppPts','plr',...PLAYER_COLS];
function setTblMode(m){tblMode=m;document.querySelectorAll('#btnYht,#btnPPeli').forEach(b=>b.classList.toggle('active',(b.id==='btnYht')===(m==='yht')));renderBothTables()}
function aggregateRows(rows,groupKey){const map={};rows.forEach(r=>{const raw=r[groupKey];if(!raw)return;const key=groupKey===COL.vastustaja?`${r[COL.ottelu]}__${raw}`:raw;if(!map[key])map[key]={label:raw,gameNum:n(r[COL.ottelu]),gp:new Set(),advGames:new Set(),minGames:new Set(),pts:0,min:0,fgm:0,fga:0,t3m:0,t3a:0,ftm:0,fta:0,orb:0,drb:0,rb:0,ast:0,stl:0,blk:0,to:0,pf:0,plr:new Set(),oppPts:n(r[COL.vastPts])};const m=map[key];m.gp.add(r[COL.ottelu]);m.pts+=n(r[COL.pisteet]);const mins=parseMinutes(r['Pl. Time']);if(mins!=null){m.min+=mins;m.minGames.add(r[COL.ottelu])}if(hasAdvancedStats(r))m.advGames.add(r[COL.ottelu]);['fgm','fga','t3m','t3a','ftm','fta','orb','drb','rb','ast','stl','blk','to','pf'].forEach(k=>m[k]+=n(r[COL[k]]));if(r[COL.nimi])m.plr.add(r[COL.nimi])});return Object.values(map).map(m=>{const div=(v,d)=>tblMode==='ppeli'?+(v/Math.max(d,1)).toFixed(1):+v.toFixed(1),pct=(a,b)=>b?+(a/b*100).toFixed(1):'-',adv=m.advGames.size>0,t2m=m.fgm-m.t3m,t2a=m.fga-m.t3a;return{label:m.label,displayLabel:groupKey===COL.vastustaja?`O${m.gameNum} ${m.label}`:m.label,gameNum:m.gameNum,gp:m.gp.size,oppPts:m.oppPts,plr:m.plr.size||'-',pts:div(m.pts,m.gp.size),min:m.minGames.size?div(m.min,m.minGames.size):'-',fgm:adv?div(m.fgm,m.advGames.size):'-',fga:adv?div(m.fga,m.advGames.size):'-',fgpct:adv?pct(m.fgm,m.fga):'-',t2m:adv?div(t2m,m.advGames.size):'-',t2a:adv?div(t2a,m.advGames.size):'-',t2pct:adv?pct(t2m,t2a):'-',t3m:adv?div(m.t3m,m.advGames.size):'-',t3a:adv?div(m.t3a,m.advGames.size):'-',t3pct:adv?pct(m.t3m,m.t3a):'-',ftm:adv?div(m.ftm,m.advGames.size):'-',fta:adv?div(m.fta,m.advGames.size):'-',ftpct:adv?pct(m.ftm,m.fta):'-',orb:adv?div(m.orb,m.advGames.size):'-',drb:adv?div(m.drb,m.advGames.size):'-',rb:adv?div(m.rb,m.advGames.size):'-',ast:adv?div(m.ast,m.advGames.size):'-',stl:adv?div(m.stl,m.advGames.size):'-',blk:adv?div(m.blk,m.advGames.size):'-',to:adv?div(m.to,m.advGames.size):'-',pf:adv?div(m.pf,m.advGames.size):'-'}})}
function renderTable(data,tbodyId,cols,isOpp=false){const key=isOpp?sKeyO:sKeyP,desc=isOpp?sDescO:sDescP;data.sort((a,b)=>{const av=key==='label'?(isOpp?a.gameNum:a.label):(a[key]==='-'?-Infinity:a[key]);const bv=key==='label'?(isOpp?b.gameNum:b.label):(b[key]==='-'?-Infinity:b[key]);return typeof av==='string'?(desc?bv.localeCompare(av):av.localeCompare(bv)):(desc?bv-av:av-bv)});document.getElementById(tbodyId).innerHTML=data.map(r=>`<tr onclick="${isOpp?`clickOpp('${r.gameNum}__${String(r.label).replace(/'/g,"\\'")}')`:`clickPlayer('${String(r.label).replace(/'/g,"\\'")}')`}"><td>${r.displayLabel}</td>${!isOpp?`<td>${r.gp}</td>`:''}${cols.map(c=>`<td>${r[c]}</td>`).join('')}</tr>`).join('')}
function renderBothTables(){const base=rowsForSelectedSeasons(selectedSeasons);const oppName=activeOpp?activeOpp.split('__').slice(1).join('__'):null,oppGame=activeOpp?+activeOpp.split('__')[0]:null;renderTable(aggregateRows(activeOpp?base.filter(r=>r[COL.vastustaja]===oppName&&n(r[COL.ottelu])===oppGame):base,COL.nimi),'tbP',PLAYER_COLS,false);renderTable(aggregateRows(activePlayer?base.filter(r=>r[COL.nimi]===activePlayer):base,COL.vastustaja),'tbO',OPP_COLS,true);document.getElementById('p1label').textContent=activeOpp?`Pelaajat — ${oppName}`:'Pelaajat';document.getElementById('p2label').textContent=activePlayer?`Vastustajat — ${activePlayer}`:'Vastustajat'}
function clickPlayer(name){activePlayer=activePlayer===name?null:name;activeOpp=null;renderBothTables()}
function clickOpp(key){activeOpp=activeOpp===key?null:key;activePlayer=null;renderBothTables()}
function clearFilter(){activePlayer=null;activeOpp=null;renderBothTables()}
function srtP(k){if(sKeyP===k)sDescP=!sDescP;else{sKeyP=k;sDescP=true}renderBothTables()}
function srtO(k){if(sKeyO===k)sDescO=!sDescO;else{sKeyO=k;sDescO=false}renderBothTables()}
function csvValue(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function downloadCSV(){const rows=rowsForSelectedSeasons(selectedSeasons),headers=['Player','Game','Opponent','Home_Away','Result','Season','Team_Score','Opp_Score','Date','Minutes','Advanced_Stats','PTS','FGM','FGA','3PM','3PA','FTM','FTA','ORB','DRB','REB','AST','STL','BLK','TOV','PF'];const body=rows.map(r=>{const adv=hasAdvancedStats(r);return [r[COL.nimi]??'',r[COL.ottelu]??'',r[COL.vastustaja]??'',r[COL.kotiv]??'',r[COL.tulos]??'',r[COL.kausi]??'',r[COL.omaPts]??'',r[COL.vastPts]??'',r['Pvm']??'',parseMinutes(r['Pl. Time'])??'',adv?1:0,r[COL.pisteet]??0,...['fgm','fga','t3m','t3a','ftm','fta','orb','drb','rb','ast','stl','blk','to','pf'].map(k=>adv?(r[COL[k]]??0):'')].map(csvValue).join(',')});const blob=new Blob([[headers.join(','),...body].join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`PP_Stats_${[...selectedSeasons].join('_')||curSeason}.csv`;a.click();URL.revokeObjectURL(url)}
