/*
  Data-driven 4-out / 1-in teaching scenarios.
  The game engine only expects this schema; add new objects here without changing game.js.

  positions: player number -> named court spot
  ballFrom / ballTo: named court spots used for the trigger animation
  automaticMoves: optional teammate moves that happen with the trigger
  controlledPlayer: 1=PG, 2=SG, 3=SF, 4=PF, 5=C
*/
window.SCENARIOS = [
  {
    id: "pass-cut-left",
    title: "Pass & cut vasemmalta slotilta",
    system: "4out1in",
    difficulty: 1,
    tags: ["slot-wing", "basket-cut"],
    positions: {1:"leftSlot",2:"rightSlot",3:"leftWing",4:"rightCorner",5:"rightDunker"},
    ballFrom: "leftSlot",
    ballTo: "leftWing",
    triggerText: "PG syöttää left slot → left wing.",
    controlledPlayer: 1,
    correctAction: "basket cut",
    correctPosition: "paint",
    explanation: "Syötön jälkeen leikkaa korille. Älä jää täyttämään samaa kaistaa pallon viereen."
  },
  {
    id: "fill-right-wing",
    title: "Täytä vapautunut oikea wing",
    system: "4out1in",
    difficulty: 1,
    tags: ["wing-corner", "fill"],
    positions: {1:"rightSlot",2:"rightWing",3:"leftSlot",4:"rightCorner",5:"leftDunker"},
    ballFrom: "rightWing",
    ballTo: "rightCorner",
    triggerText: "SG syöttää right wing → right corner ja leikkaa korille.",
    automaticMoves: {2:"paint"},
    controlledPlayer: 1,
    correctAction: "fill",
    correctPosition: "rightWing",
    explanation: "Kun wing vapautuu basket cutin jälkeen, täytä se slotilta ja säilytä perimeter-spacing."
  },
  {
    id: "slot-slot-cut-pg",
    title: "Slot-to-slot: syöttäjä leikkaa",
    system: "4out1in",
    difficulty: 1,
    tags: ["slot-slot", "basket-cut"],
    positions: {1:"leftSlot",2:"rightSlot",3:"leftCorner",4:"rightCorner",5:"paint"},
    ballFrom: "leftSlot",
    ballTo: "rightSlot",
    triggerText: "PG syöttää left slot → right slot.",
    controlledPlayer: 1,
    correctAction: "basket cut",
    correctPosition: "paint",
    explanation: "Slot-to-slot-syötön jälkeen tee terävä basket cut ennen kuin perimeter täyttyy uudelleen."
  },
  {
    id: "pg-lift-middle-drive",
    title: "Weakside lift middle drivessa",
    system: "4out1in",
    difficulty: 2,
    tags: ["drive-middle", "lift"],
    positions: {1:"leftSlot",2:"rightWing",3:"leftWing",4:"rightCorner",5:"leftDunker"},
    ballFrom: "rightWing",
    ballTo: "paint",
    triggerText: "SG ajaa right wingiltä keskelle.",
    controlledPlayer: 1,
    correctAction: "lift",
    correctPosition: "top",
    explanation: "Middle drive vetää apupuolustusta sisään. Lift topiin avaa palautussyötön ja pitää ajolinjan puhtaana."
  },

  {
    id: "sg-wing-corner-cut",
    title: "Wing-to-corner: basket cut",
    system: "4out1in",
    difficulty: 1,
    tags: ["wing-corner", "basket-cut"],
    positions: {1:"rightSlot",2:"rightWing",3:"leftSlot",4:"rightCorner",5:"leftDunker"},
    ballFrom: "rightWing",
    ballTo: "rightCorner",
    triggerText: "SG syöttää right wing → right corner.",
    controlledPlayer: 2,
    correctAction: "basket cut",
    correctPosition: "paint",
    explanation: "Syöttäjä reagoi heti: leikkaa korille ja pakota puolustus kääntämään päätä."
  },
  {
    id: "sg-drift-baseline",
    title: "Drift baseline drivessa",
    system: "4out1in",
    difficulty: 2,
    tags: ["drive-baseline", "drift"],
    positions: {1:"leftSlot",2:"rightWing",3:"leftWing",4:"leftCorner",5:"paint"},
    ballFrom: "leftWing",
    ballTo: "leftDunker",
    triggerText: "SF ajaa left wingiltä baselinea.",
    controlledPlayer: 2,
    correctAction: "drift",
    correctPosition: "rightCorner",
    explanation: "Vastakkaisen puolen perimeter-pelaaja driftaa kulmaan, jotta baseline-ajolla on selkeä skip- ja corner-syöttö."
  },
  {
    id: "sg-post-spacing",
    title: "Post entry: säilytä skip-linja",
    system: "4out1in",
    difficulty: 2,
    tags: ["post-entry", "spacing"],
    positions: {1:"leftWing",2:"rightSlot",3:"leftCorner",4:"rightCorner",5:"paint"},
    ballFrom: "leftWing",
    ballTo: "paint",
    triggerText: "Pallo syötetään left wingiltä postiin.",
    controlledPlayer: 2,
    correctAction: "stay",
    correctPosition: "rightSlot",
    explanation: "Weakside slot säilyttää etäisyyden ja skip-syöttöikkunan. Älä kutista kenttää ilman syytä."
  },
  {
    id: "sg-backcut",
    title: "Denied wing: back cut",
    system: "4out1in",
    difficulty: 2,
    tags: ["back-cut", "denial"],
    positions: {1:"rightSlot",2:"rightWing",3:"leftSlot",4:"leftCorner",5:"rightDunker"},
    ballFrom: "rightSlot",
    ballTo: "rightSlot",
    triggerText: "SG:n wing-syöttölinja kielletään aggressiivisesti.",
    controlledPlayer: 2,
    correctAction: "back cut",
    correctPosition: "paint",
    explanation: "Kun puolustaja top-lockaa tai ylipelaa syöttölinjan, back cut rankaisee denialista."
  },

  {
    id: "sf-hold-corner",
    title: "Corner spacing: pysy leveänä",
    system: "4out1in",
    difficulty: 1,
    tags: ["slot-wing", "spacing"],
    positions: {1:"leftSlot",2:"rightSlot",3:"leftCorner",4:"rightCorner",5:"paint"},
    ballFrom: "leftSlot",
    ballTo: "leftWing",
    triggerText: "Pallo liikkuu left slot → left wing.",
    controlledPlayer: 3,
    correctAction: "stay",
    correctPosition: "leftCorner",
    explanation: "Corner pysyy leveänä. Pallon viereen nouseminen tukkisi wingin ajotilan."
  },
  {
    id: "sf-lift-own-side",
    title: "Lift ajon taakse",
    system: "4out1in",
    difficulty: 2,
    tags: ["drive-middle", "lift"],
    positions: {1:"rightSlot",2:"rightWing",3:"leftCorner",4:"leftWing",5:"rightDunker"},
    ballFrom: "leftWing",
    ballTo: "paint",
    triggerText: "PF ajaa left wingiltä keskelle.",
    controlledPlayer: 3,
    correctAction: "lift",
    correctPosition: "leftWing",
    explanation: "Kun wing ajaa keskelle, corner liftää ajon taakse ja tarjoaa helpon kick-out-syötön."
  },
  {
    id: "sf-drift-opposite",
    title: "Opposite drift baseline-ajossa",
    system: "4out1in",
    difficulty: 2,
    tags: ["drive-baseline", "drift"],
    positions: {1:"rightSlot",2:"rightCorner",3:"leftWing",4:"rightWing",5:"paint"},
    ballFrom: "rightWing",
    ballTo: "rightDunker",
    triggerText: "PF ajaa right wingiltä baselinea.",
    controlledPlayer: 3,
    correctAction: "drift",
    correctPosition: "leftCorner",
    explanation: "Vastakkaiselta wingiltä drift corneriin pidentää apupuolustuksen rotaatiota ja avaa skipin."
  },
  {
    id: "sf-replace-left-slot",
    title: "Replace basket cutin jälkeen",
    system: "4out1in",
    difficulty: 1,
    tags: ["fill", "replace"],
    positions: {1:"leftSlot",2:"rightSlot",3:"leftWing",4:"rightCorner",5:"leftDunker"},
    ballFrom: "leftSlot",
    ballTo: "rightSlot",
    triggerText: "PG syöttää slot-to-slot ja leikkaa korille.",
    automaticMoves: {1:"paint"},
    controlledPlayer: 3,
    correctAction: "replace",
    correctPosition: "leftSlot",
    explanation: "Kun left slot tyhjenee cutilla, lähin perimeter-pelaaja täyttää vapaan spotin."
  },

  {
    id: "pf-fill-wing",
    title: "Corner → wing fill",
    system: "4out1in",
    difficulty: 1,
    tags: ["fill", "wing"],
    positions: {1:"leftSlot",2:"rightSlot",3:"leftWing",4:"leftCorner",5:"rightDunker"},
    ballFrom: "leftWing",
    ballTo: "rightSlot",
    triggerText: "SF syöttää left wing → right slot ja basket-cuttaa.",
    automaticMoves: {3:"paint"},
    controlledPlayer: 4,
    correctAction: "fill",
    correctPosition: "leftWing",
    explanation: "Täytä vapautunut wing cornerista, jotta neljä perimeter-spottia pysyvät tasapainossa."
  },
  {
    id: "pf-corner-to-wing",
    title: "Replace wing-to-slot-liikkeessä",
    system: "4out1in",
    difficulty: 1,
    tags: ["wing-slot", "replace"],
    positions: {1:"leftSlot",2:"rightSlot",3:"rightWing",4:"rightCorner",5:"leftDunker"},
    ballFrom: "rightWing",
    ballTo: "rightSlot",
    triggerText: "SF syöttää right wing → right slot ja leikkaa.",
    automaticMoves: {3:"paint"},
    controlledPlayer: 4,
    correctAction: "replace",
    correctPosition: "rightWing",
    explanation: "Kun wing leikkaa syötön jälkeen, corner nousee täyttämään vapaan wingin."
  },
  {
    id: "pf-lift-corner",
    title: "Corner lift middle drivessa",
    system: "4out1in",
    difficulty: 2,
    tags: ["drive-middle", "lift"],
    positions: {1:"leftSlot",2:"rightWing",3:"leftWing",4:"rightCorner",5:"leftDunker"},
    ballFrom: "rightWing",
    ballTo: "paint",
    triggerText: "SG ajaa oikealta wingiltä keskelle.",
    controlledPlayer: 4,
    correctAction: "lift",
    correctPosition: "rightWing",
    explanation: "Ball-side corner liftää wingille ajon taakse. Se avaa lyhyen kick-outin ja estää kahden hyökkääjän kasaantumisen baselineen."
  },
  {
    id: "pf-post-relocate",
    title: "Post entry: relocate corneriin",
    system: "4out1in",
    difficulty: 3,
    tags: ["post-entry", "relocate"],
    positions: {1:"leftSlot",2:"rightSlot",3:"rightCorner",4:"leftWing",5:"paint"},
    ballFrom: "leftWing",
    ballTo: "paint",
    triggerText: "PF syöttää left wingiltä postiin ja pallo on sisällä.",
    controlledPlayer: 4,
    correctAction: "relocate",
    correctPosition: "leftCorner",
    explanation: "Syötön jälkeen relocate corneriin kasvattaa postin tilaa ja muuttaa syöttökulmaa mahdollista kick-outia varten."
  },

  {
    id: "c-clear-baseline",
    title: "Big clears baseline driven",
    system: "4out1in",
    difficulty: 2,
    tags: ["drive-baseline", "dunker"],
    positions: {1:"leftSlot",2:"rightSlot",3:"leftWing",4:"rightCorner",5:"paint"},
    ballFrom: "leftWing",
    ballTo: "leftDunker",
    triggerText: "SF ajaa vasenta baselinea kohti koria.",
    controlledPlayer: 5,
    correctAction: "clear",
    correctPosition: "rightDunker",
    explanation: "Sisäpelaaja siirtyy pois ajolinjalta vastakkaiseen dunker spottiin ja säilyttää samalla viimeistelyuhan."
  },
  {
    id: "c-slide-middle",
    title: "Big slides behind middle drive",
    system: "4out1in",
    difficulty: 2,
    tags: ["drive-middle", "dunker"],
    positions: {1:"leftSlot",2:"rightWing",3:"leftWing",4:"rightCorner",5:"paint"},
    ballFrom: "rightWing",
    ballTo: "paint",
    triggerText: "SG ajaa oikealta wingiltä keskelle.",
    controlledPlayer: 5,
    correctAction: "slide",
    correctPosition: "leftDunker",
    explanation: "Big liukuu ajon vastakkaiselle puolelle: pois pallon ajolinjalta, mutta valmiiksi dump-off-syöttöön."
  },
  {
    id: "c-duck-in",
    title: "Weakside duck-in",
    system: "4out1in",
    difficulty: 3,
    tags: ["slot-slot", "duck-in"],
    positions: {1:"leftSlot",2:"rightSlot",3:"leftCorner",4:"rightCorner",5:"leftDunker"},
    ballFrom: "leftSlot",
    ballTo: "rightSlot",
    triggerText: "Pallo vaihtaa puolta left slot → right slot.",
    controlledPlayer: 5,
    correctAction: "duck in",
    correctPosition: "paint",
    explanation: "Kun pallo vaihtaa puolta ja keskusta aukeaa, sisäpelaaja voi duck-inilla hakea syvän sealin maalista."
  },
  {
    id: "c-clear-backcut",
    title: "Clear lane back cutille",
    system: "4out1in",
    difficulty: 3,
    tags: ["back-cut", "dunker"],
    positions: {1:"rightSlot",2:"rightWing",3:"leftSlot",4:"leftCorner",5:"paint"},
    ballFrom: "rightSlot",
    ballTo: "rightSlot",
    triggerText: "SG:n right wing kielletään ja hän aloittaa back cutin.",
    automaticMoves: {2:"paint"},
    controlledPlayer: 5,
    correctAction: "clear",
    correctPosition: "leftDunker",
    explanation: "Kun perimeter-pelaaja back-cuttaa, big avaa korille kaistan siirtymällä pois maalialueen keskeltä."
  }
];